Wenzel/awesome-virtualization

README.md

QEMU is an important layer in the virtualization world

add link to QEMU

---

README.md

Hey,
I added links for the papers

Add links for papers

---

README.md

Hey, here is part 6 of Hypervisor From Scratch by Sina & Shahriar

Add part 6 of Hypervisor From Scratch

---

README.md

All updates related to the MemoryRanger and my hypervisor security research papers have been added.

MemoryRanger

---

README.md

Add link to Awesome Hyper-V Exploitation list of resources for fuzzing, vulnerability research and exploit development targeting Hyper-V.

Add Awesome Hyper-V Exploitation list

---

README.md

add Intel Nemu
https://github.com/intel/nemu

add Intel nemu

---

README.md

https://bitbucket.org/bitvisor/bitvisor/

add BitVisor

---

README.md

Add Siemens Jailhouse
https://github.com/siemens/jailhouse

add jailhouse

---

README.md

https://www.usenix.org/system/files/sec19-li-shih-wei.pdf
https://www.youtube.com/watch?v=QL98ZmDeYMw

Add HypSec

---

README.md

https://github.com/dgreid/crosvm

Add crosvm

---

README.md

https://github.com/firecracker-microvm/firecracker

Add Firecracker

---

README.md

https://github.com/rust-vmm/community

add rust-vmm

---

README.md

https://github.com/google/gvisor

Add gvisor

---

README.md

Add Xvisor

---

README.md

https://revers.engineering/7-days-to-virtualization-a-series-on-hypervisor-development/
by @aaximus and @ajkhoury

Add 5 Days to Virtualization series

---

README.md

https://github.com/gamozolabs/orange_slice

add orange_slice

---

README.md

https://github.com/cloud-hypervisor/cloud-hypervisor

add cloud-hypervisor

---

README.md

https://github.com/changeofpace/VivienneVMM

add VivienneVMM

---

README.md

https://github.com/GiantVM/homepage

add GiantVM

---

README.md

https://github.com/tandasat/MiniVisorPkg

add MiniVisorPkg

---

README.md

add VMCS Layout PDF from @LordNoteworthy

add documentation section

---

README.md

https://github.com/Bareflank/MicroV

add microV

---

README.md

https://developer.amd.com/sev/

chronology: add SEV, SEV-ES and SEV-SNP

---

README.md

add drakvuf project https://github.com/tklengyel/drakvuf

add DRAKVUF project

---

README.md

https://github.com/gerhart01/Hyper-V-Internals/blob/master/HyperResearchesHistory.md
thanks @gerhart01

hyper-v: add internals researches history by gerhart

---

README.md

https://foxhex0ne.blogspot.com/2020/05/hyper-v-0x1-hypercalls-part-1.html by @FoxHex0ne

hyper-v: add article on hypercalls

---

README.md

hi Wenzel, 
here is my another virtualization project which utilizes dynamic binary translation techniques to translate riscv32 instructions to x86_64 instructions, it is able to run a risc-v linux.
Thanks,
Link

Zelda.RISCV: Dynamic Binary Translation for RISCV32 over x86_64

---

README.md

https://www.cpl0.com/blog/?p=46

attack: add escape via NMI

---

README.md

https://revers.engineering/patchguard-detection-of-hypervisor-based-instrospection-p1/
https://revers.engineering/patchguard-detection-of-hypervisor-based-instrospection-p2/
by @daaximus
by @ajkhoury
by @everdox

add patchguard detection introspection articles

---

README.md

https://github.com/hermitcore/uhyve

research: add uhyve

---

README.md

https://re.alisa.sh/notes/Hyper-V-LIS.html by @badd1e

hyper-v: add article on LIS

---

README.md

https://github.com/mythril-hypervisor/mythril by @ALSchwalm

add mythril

---

README.md

https://github.com/napocahv/napoca

research: add Napoca

---

README.md

https://github.com/Cisco-Talos/Barbervisor
blog: https://blog.talosintelligence.com/2020/08/barbervisor.html

add barbervisor

---

README.md

https://github.com/honorarybot/VmxCaps by @honorarybot

Intel: add VMX Caps

---

README.md

add Hypervisor Vulnerability Research slides by @badd1e
https://alisa.sh/slides/HypervisorVulnerabilityResearch2020.pdf

README: add Hypervisor Vulnerability Research slides

---

README.md

https://revers.engineering/mmu-ept-technical-details/
by @daaximus

README: add MMU Virtualization via Intel EPT

---

README.md

https://github.com/Zero-Tang/NoirVisor
by @Zero-Tang

README: add NoirVisor

---

README.md

add https://github.com/udosteinberg/NOVA from @udosteinberg

research: add NOVA hypervisor

---

README.md

add Hedron hypervisor:
https://github.com/cyberus-technology/hedron

research: add Hedron

---

README.md

course: add Virtualization and Computing Lectures from Youtube

---

README.md

We should not miss this groundbreaking work by ITL.
It misses a proper landing page, but their contribution cannot be disregarded, and so, linking to source code alone is worth for capturing the history.

research: add Blue Pill

---

README.md

This is a great book we cannot miss. It is modern (published in 2017), discusses device virtualization technologies and ARM virtualization extensibility. I personally recommend this book over the others listed here.

book: add Hardware and Software Support for Virtualization

---

README.md

Not sure if this is the right section to add the tool in the readme since it mainly features blogs/talks instead of projects, so please ask me to edit the PR to fit it as intended.

added vmaware
